language:
- scala
sudo: required
dist: trusty
jdk:
- oraclejdk8
scala:
- 2.12.7
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sbt
script:
- ./gradlew :beam-runners-gearpump:validatesRunnerStreaming    
install:
- git clone https://github.com/manuzhang/gearpump -b app_result && cd gearpump && sbt publishM2 && cd -
